"""Private per-turn protocol for XiaoKe voice-call replies.

The token is generated by the voice-call server and is never part of the user
history record.  It is shown only in the terminal prompt for that exact turn,
then echoed by the *formal* channel reply.  This lets the voice waiter ignore
terminal stop-hook chatter and replies from older turns.
"""

from __future__ import annotations

import re
import secrets
import os
import stat
import threading
import time
from pathlib import Path
from typing import Callable, TypeVar


VOICE_CALL_SOURCE = "android-app:voice-call"
VOICE_REPLY_SOURCE = "cc-companion-channel"
VOICE_REPLY_TOKEN_FIELD = "voice_reply_token"
VOICE_REPLY_TOKEN_HEX_LENGTH = 32
VOICE_INTERNAL_TOKEN_HEX_LENGTH = 64
VOICE_INTERNAL_HEADER = "X-Voice-Internal-Token"
VOICE_INTERNAL_TOKEN_PATH = Path(__file__).resolve().parent / "state" / "voice_internal_token"
VOICE_REPLY_RESERVED_METADATA = frozenset(
    {"voice_reply_token", "voice_reply_v", "voice_reply_text"}
)
VOICE_REPLY_PENDING_TTL_SEC = 300.0

_TOKEN_RE = re.compile(r"[0-9a-f]{32}\Z")
_REPLY_MARKER_RE = re.compile(r"\A\[\[CCC_VOICE_REPLY:([0-9a-f]{32})\]\]")
_INTERNAL_TOKEN_RE = re.compile(r"[0-9a-f]{64}\Z")

_T = TypeVar("_T")


class VoiceInternalTokenError(RuntimeError):
    """The private voice-service credential is missing or unsafe."""


class VoiceReplyNotPending(RuntimeError):
    """A formal reply did not atomically claim the current voice turn."""


def generate_voice_reply_token() -> str:
    """Return one unpredictable, canonical token for a single voice turn."""

    return secrets.token_hex(VOICE_REPLY_TOKEN_HEX_LENGTH // 2)


def normalize_voice_reply_token(value: object) -> str:
    """Accept only the exact lowercase-hex token form generated above."""

    if not isinstance(value, str) or not _TOKEN_RE.fullmatch(value):
        return ""
    return value


def sanitize_voice_metadata(value: object) -> dict | None:
    """Remove server-reserved voice fields from untrusted metadata."""

    if not isinstance(value, dict):
        return None
    cleaned = {
        key: item
        for key, item in value.items()
        if key not in VOICE_REPLY_RESERVED_METADATA
    }
    return cleaned or None


def _read_private_internal_token(path: Path) -> str:
    try:
        info = path.lstat()
    except Exception as exc:
        raise VoiceInternalTokenError("voice internal credential is unavailable") from exc
    if stat.S_ISLNK(info.st_mode) or not stat.S_ISREG(info.st_mode) or info.st_mode & 0o077:
        raise VoiceInternalTokenError("voice internal credential has unsafe permissions")
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags)
        try:
            opened = os.fstat(fd)
            if not stat.S_ISREG(opened.st_mode) or opened.st_mode & 0o077:
                raise VoiceInternalTokenError("voice internal credential became unsafe")
            raw = os.read(fd, VOICE_INTERNAL_TOKEN_HEX_LENGTH + 2).decode("ascii").strip()
        finally:
            os.close(fd)
    except VoiceInternalTokenError:
        raise
    except Exception as exc:
        raise VoiceInternalTokenError("voice internal credential is unavailable") from exc
    if not _INTERNAL_TOKEN_RE.fullmatch(raw):
        raise VoiceInternalTokenError("voice internal credential is invalid")
    return raw


def load_or_create_voice_internal_token(path: str | Path = VOICE_INTERNAL_TOKEN_PATH) -> str:
    """Load or atomically create the private credential shared by local services.

    Creation uses a fully-written 0600 temporary file followed by an atomic
    hard-link create, so concurrent push/voice startups never replace each
    other's credential or observe a partially-written target.
    """

    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() or target.is_symlink():
        return _read_private_internal_token(target)

    token = secrets.token_hex(VOICE_INTERNAL_TOKEN_HEX_LENGTH // 2)
    tmp = target.parent / f".{target.name}.{os.getpid()}.{secrets.token_hex(8)}.tmp"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_CLOEXEC", 0)
    fd = os.open(tmp, flags, 0o600)
    try:
        os.fchmod(fd, 0o600)
        os.write(fd, (token + "\n").encode("ascii"))
        os.fsync(fd)
    finally:
        os.close(fd)
    try:
        try:
            os.link(tmp, target)
        except FileExistsError:
            pass
    finally:
        try:
            tmp.unlink()
        except FileNotFoundError:
            pass
    return _read_private_internal_token(target)


class PendingVoiceReplies:
    """Process-local one-shot claim registry for XiaoKe formal voice replies."""

    def __init__(self, *, ttl_seconds: float = VOICE_REPLY_PENDING_TTL_SEC) -> None:
        self._lock = threading.RLock()
        self._ttl_seconds = max(1.0, float(ttl_seconds))
        self._pending: dict[str, object] = {}
        self._suppressed_streams: dict[str, float] = {}

    def _pending_valid_locked(self, token: str, now: float) -> bool:
        current = str(self._pending.get("token") or "")
        created = float(self._pending.get("created_at") or 0.0)
        if not current or now - created > self._ttl_seconds:
            self._pending = {}
            return False
        return current == token

    def register(self, token: str, *, user_ts: str = "") -> None:
        valid = normalize_voice_reply_token(token)
        if not valid:
            raise ValueError("invalid voice reply token")
        with self._lock:
            self._pending = {
                "token": valid,
                "user_ts": str(user_ts or ""),
                "created_at": time.monotonic(),
            }

    def cancel(self, token: str) -> bool:
        return self.cancel_details(token) is not None

    def cancel_details(self, token: str) -> dict[str, str] | None:
        valid = normalize_voice_reply_token(token)
        with self._lock:
            if not valid or not self._pending_valid_locked(valid, time.monotonic()):
                return None
            details = {
                "token": valid,
                "user_ts": str(self._pending.get("user_ts") or ""),
            }
            self._pending = {}
            return details

    def is_pending(self, token: str) -> bool:
        valid = normalize_voice_reply_token(token)
        if not valid:
            return False
        with self._lock:
            return self._pending_valid_locked(valid, time.monotonic())

    def has_pending(self) -> bool:
        with self._lock:
            token = str(self._pending.get("token") or "")
            return bool(token and self._pending_valid_locked(token, time.monotonic()))

    def claim_and_run(self, token: str, operation: Callable[[], _T]) -> _T:
        """Run one history append while holding the one-shot claim lock."""

        valid = normalize_voice_reply_token(token)
        with self._lock:
            if not valid or not self._pending_valid_locked(valid, time.monotonic()):
                raise VoiceReplyNotPending("formal voice reply is not pending")
            result = operation()
            self._pending = {}
            return result

    def should_suppress_stream(self, stream_id: str, text: str = "") -> bool:
        """Fence all stream frames for a pending voice turn and its stream id."""

        stream = str(stream_id or "")[:200]
        now = time.monotonic()
        with self._lock:
            self._suppressed_streams = {
                key: expiry
                for key, expiry in self._suppressed_streams.items()
                if expiry > now
            }
            marker_token = parse_voice_reply(text)[1]
            suppress = (
                bool(stream and stream in self._suppressed_streams)
                or self.has_pending()
                or bool(marker_token)
            )
            if suppress and stream:
                self._suppressed_streams[stream] = now + self._ttl_seconds
            return suppress


def build_voice_reply_instruction(token: str) -> str:
    """Build the private terminal-only instruction for a validated token."""

    valid = normalize_voice_reply_token(token)
    if not valid:
        raise ValueError("invalid voice reply token")
    marker = f"[[CCC_VOICE_REPLY:{valid}]]"
    return (
        "[CCC 通话正式回复协议：这是一轮语音通话。终端里的思考、工具过程和自言自语"
        "都不是给用户的语音回复，不要让 stop hook 代替正式答复。请只通过 "
        "cc-companion channel 的非流式单次 reply 发送最终要对用户说的正文，"
        "不要发送 reply_chunk；并且必须把 "
        f"{marker} 放在正式回复的第一个字符；marker 后再写正文。]"
    )


def parse_voice_reply(text: object) -> tuple[str, str]:
    """Return ``(clean_text, token)`` for a marker at byte/character zero.

    A marker elsewhere is ordinary user-visible text and yields no token.  One
    optional line break directly after the marker is consumed before the clean
    body is stripped.
    """

    if not isinstance(text, str):
        return "", ""
    match = _REPLY_MARKER_RE.match(text)
    if match is None:
        return text, ""
    remainder = text[match.end() :]
    if remainder.startswith("\r\n"):
        remainder = remainder[2:]
    elif remainder.startswith(("\r", "\n")):
        remainder = remainder[1:]
    return remainder.strip(), match.group(1)
